// Wave 4.2-A-2 snapshot test — locks game_recap output for event
// a0b2d68a (10U Blue vs Resurrection White 4AB, 2026-05-02 W 2-0,
// POG Giuseppe, coach_highlight "defense"). Expected content_sections
// is hand-authored against the contract spec, not generated by running
// the new code, so a refactor that drifts from spec surfaces here.

import { describe, expect, it } from 'vitest';
import { composeGameRecap, resolveGameRecap } from '../gameRecap';
import { mockClient } from './mockSupabase';
import event from './fixtures/game_recap_may_2_10u_blue/event.json';
import game_result from './fixtures/game_recap_may_2_10u_blue/game_result.json';
import player_of_game from './fixtures/game_recap_may_2_10u_blue/player_of_game.json';
import tournament from './fixtures/game_recap_may_2_10u_blue/tournament.json';
import recipients from './fixtures/game_recap_may_2_10u_blue/recipients.json';
import player_guardians from './fixtures/game_recap_may_2_10u_blue/player_guardians.json';
import coaches from './fixtures/game_recap_may_2_10u_blue/coaches.json';
import organization from './fixtures/game_recap_may_2_10u_blue/organization.json';
import expectedContentSections from './fixtures/game_recap_may_2_10u_blue/expected_content_sections.json';

const EVENT_ID = 'a0b2d68a-cd2a-4d15-9922-5c2becc0c806';
const NOW = new Date('2026-05-10T14:00:00Z');
const FIXTURES = { event, game_result, player_of_game, tournament, recipients, player_guardians, coaches, organization };
const norm = (v) => JSON.parse(JSON.stringify(v));

describe('game_recap resolver — snapshot vs hand-authored expected output', () => {
  it('slices[0] is Amanda Bauer (lowest guardian_id under ASC), 21 total recipients', async () => {
    const { slices } = await resolveGameRecap(
      { eventId: EVENT_ID, pilotOnly: false },
      { supabase: mockClient(FIXTURES), now: NOW },
    );
    expect(slices.length).toBe(21);
    expect(slices[0].guardian_id).toBe('02810181-4676-406b-8ddc-84a530c5bc90');
    expect(slices[0].email).toBe('amandajoybauer@gmail.com');
    expect(slices[0].kid_first_names).toEqual(['Shane']);
    expect(slices[0].team_id).toBe('13abc98d-5e88-4fe0-8929-690add6e2bdd');
  });

  it('compose for slices[0] matches hand-authored expected output', async () => {
    const { context, slices } = await resolveGameRecap(
      { eventId: EVENT_ID, pilotOnly: false },
      { supabase: mockClient(FIXTURES), now: NOW },
    );
    const { subject, content_sections } = composeGameRecap(context, slices[0], {});
    expect(subject).toBe('Recap — 10U Blue beat Resurrection White 4AB, 2-0');
    expect(norm(content_sections)).toEqual(expectedContentSections);
  });
});
